### ISSUE TITLE
如何让 VSCode 打开文件始终在新标签页打开？

### ISSUE THREAD

**Issue by isLishude** [isLishude/blog#162]
VSCode 有一个默认设定，单击一个右侧侧边栏的文件是预览模式，如果不输入任何任何文本就始终保持预览模式。

预览模式是的打开一个新文件，然后再打开一个新文件，第二个就会占用第一个窗口。详细信息可以查看：https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

文件处于预览模式有个标识，就是标题栏的文件名称是斜体的，

如何关闭？在设置文件里设置 `workbench.editor.enablePreview` 为 false 即可，这是全局设置的，每次都是打开新 tab。

不过还有个简单的方式，那就是**双击新文件**就是不以预览模式打开。如果已经打开，那么**双击标题栏的文件名称**也可以。

**Comment by leeguooooo** [comment]
还有一个设置是控制显示tabs
```
 "workbench.editor.showTabs": true,
```

**Comment by sjhsbhqf** [comment]
> 还有一个设置是控制显示tabs
> 
> ```
>  "workbench.editor.showTabs": true,
> ```

在 Visual Studio Code (VSCode) 中，配置项 `"workbench.editor.showTabs"` 用于控制编辑器中是否显示标签页（tabs）。具体来说：

- **`"workbench.editor.showTabs": true`**：启用标签页显示。这意味着在编辑器顶部会显示每个打开文件的标签页，允许你通过点击标签来切换不同的文件。这是默认设置，适合需要同时处理多个文件并频繁切换的用户。

- **`"workbench.editor.showTabs": false`**：禁用标签页显示。这意味着编辑器顶部不会显示标签页，所有打开的文件将通过侧边栏的 "Open Editors" 部分或使用快捷键（如 `Ctrl+P`）来切换。这种设置适合希望最大化编辑器空间或不需要频繁切换文件的用户。

### 示例

在 `settings.json` 文件中，你可以这样配置：

```json
{
    "workbench.editor.showTabs": true
}
```

或

```json
{
    "workbench.editor.showTabs": false
}
```

### 如何修改设置

1. **打开设置**：
   - 你可以通过点击左下角的齿轮图标（设置）并选择 "Settings" 打开设置页面。
   - 或者使用快捷键 `Ctrl+,` 直接打开设置。

2. **搜索设置**：
   - 在设置页面的搜索栏中输入 `workbench.editor.showTabs`，即可找到该配置项。

3. **修改设置**：
   - 你可以直接在设置页面中切换该选项，或者点击右上角的图标打开 `settings.json` 文件进行手动编辑。

通过调整 `"workbench.editor.showTabs"` 配置项，你可以根据自己的工作习惯和需求来定制 VSCode 的界面布局，从而提高工作效率。
