### ISSUE TITLE
禁用 Mac 内置键盘和触控板

### ISSUE THREAD

**Issue by islishude** [islishude/blog#196]
最近买了个键盘，大小刚好能放在 13 英寸的 MBP 上，这样打字就舒服了很多。但是存在一个问题，直接放在上面有时候会触发内置键盘的按键。

解决方式就是禁用内置键盘，找了好多解决方案，结果都不能使用，最后找到这个软件 [tekezo/Karabiner-Elements](https://pqrs.org/osx/karabiner/)。安装后会安装两个软件，一个 Karabiner-Elements 和  Karabiner-EventViewer，要禁用内置键盘只需要用到第一个软件即可。

使用十分简单，打开软件切换到 Device 标签页，在下方的 `Disable the built-in keyboard...` 选择外接键盘即可，这个设置会在外接键盘接入时候禁用内置键盘。

<img width="994" alt="屏幕快照 2019-03-25 上午11 10 24" src="https://user-images.githubusercontent.com/24730006/54893009-cffa9680-4eee-11e9-852e-654f9fc867ae.png">

顺便一提，这个软件是[开源](https://github.com/tekezo/Karabiner-Elements)的，使用中可以安心放行一些系统权限。

keyword: disable the built-in Macbook keyboard

**Comment by greatghoul** [comment]
难道是 HHKB?

**Comment by isLishude** [comment]
不是，那个太贵了。罗技的蓝牙键盘。

**Comment by Hawstein** [comment]
我直接在 HHKB 左右两侧的底面贴一条细细的粘贴物（不知如何形容），有一定厚度，相当于直接架在内置键盘上方，这么多年都用过来了，稳定方便好用。推荐一下。

**Comment by islishude** [comment]
move to https://islishude.github.io/blog/2019/06/29/tool/%E7%A6%81%E7%94%A8-Mac-%E5%86%85%E7%BD%AE%E9%94%AE%E7%9B%98%E5%92%8C%E8%A7%A6%E6%8E%A7%E6%9D%BF/
