### ISSUE TITLE
比特币和以太坊JSON-RPC API清单

### ISSUE THREAD

**Issue by isLishude** [isLishude/blog#86]
通过使用钱包的 RPC 接口，我们可以获取很多信息，比如使用 `bitcoind getblockhash 100` 就是获取区块高度为 100 的区块哈希值，但是有的时候钱包 RPC 需要运行在包含完整区块的机器上，目前这些区块（比特币）已经达到 200G 多。

不过还好的是，很多第三方提供了 JSON-RPC 的接口服务，还封装了很多常用的接口。

# 比特币
1. https://btc.com/api-doc
2. https://blockmeta.com/docs
3. https://insight.bitpay.com/
4. https://blockchain.info/api/blockchain_api

## 以太坊
1. https://etherchain.org/api
2. https://blockmeta.com/docs

以下为一个请求比特币地址信息示例：

```shell
curl https://chain.api.btc.com/v3/address/15urYnyeJe3gwbGJ74wcX89Tz7ZtsFDVew
```

RESPONSE:
```json
{
    "err_no": 0,
    "data": {
        "address": "15urYnyeJe3gwbGJ74wcX89Tz7ZtsFDVew",
        "received": 13623974334090,
        "sent": 13623874334090,
        "balance": 100000000,
        "tx_count": 6260,
        "unconfirmed_tx_count": 0,
        "unconfirmed_received": 0,
        "unconfirmed_sent": 0,
        "unspent_tx_count": 3,
        "first_tx": "030b7d06d1dcec24d017249b6b87a457bd217150afbbe4351f8821870324d00b",
        "last_tx": "04ffa9c3875b15ceb65c2dd4ee2654c5fb65374123692362e32fac566a6b16aa"
    }
}
```

以下为一个请求以太坊地址信息示例：

```shell
curl https://etherchain.org/api/account/0xf90c9ac616ecfefb3860aaa5bc33caf9bc606441
```

RESPONSE:
```json
{
    "status": 1,
    "data": [{
        "address": "0xf90c9ac616ecfefb3860aaa5bc33caf9bc606441",
        "balance": 8451311601385754000,
        "nonce": null,
        "code": "0x",
        "name": null,
        "storage": null,
        "firstSeen": "2016-07-31T00:05:52.000Z"
    }]
}
```

本地的比特币客户端全部的 RPC 请求方法可以在[这里](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list)查看。

**Comment by isLishude** [comment]
BTC && ETH && ETC : https://blockmeta.com/docs

**Comment by isLishude** [comment]
有些服务已经不可用，待进一步完善。

**Comment by Aimeelu668** [comment]
谢谢楼楼精彩分享，我再补充一点，对于交易所这种业务型系统，选择钱包的时候需要考虑的问题，应该是安全的同时也需要快速的业务对接。相关业务上的难点有：安全、跨链整合、庞大的数据量、还有其他的业务需求比如生成地址、地址管理、资金管理、交易记录管理、充提币及回调等等。以优盾钱包——全球首款区块链交易所钱包对接开放平台为例，API一键接入，免节点同步，且以上的难点都得到了解决，业务上有主流语言的SDK可实现快速的对接： ①Java版 https://github.com/uduncloud/udun-sdk-java ②.Net版 https://github.com/uduncloud/udun-sdk-csharp ③Php版 https://github.com/uduncloud/udun-sdk-php 就安全而言，提供了Client-Gateway Solution（CGS）、Hareware-Gateway Solution（HGS）两套解决方案。
